/*
  ROaster Object. An Object containing combination information of drivers, 
  buses, route, and shift.  
*/
public class Roaster
{
  int roasterID; //In case we are going to generate many roaster. Rarely 
  int month;
  int year;
  Shift[][] shift;
  
  //Constructor. RoasterID is being generated by itself.
  public Roaster(int m, int y, Shift[][] s)
  {
    month = m;
    year = y;
    shift = s;
  }//Constructor
  
}//Roaster Object
